# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('url_suffix', models.CharField(help_text="Same as Title, But spaces and symbol converted to '-'. Ex 'Privacy policy' -> 'privacy-policy'.", max_length=50, unique=True)),
                ('html', models.TextField(blank=True, help_text='Styles avalible for h1, h2, h3, p, i and b')),
                ('css', models.TextField(blank=True)),
                ('js', models.TextField(blank=True)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField(default=False)),
                ('staff_comment', models.TextField(blank=True, help_text='Log of what is done and what needs to be done.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAboutPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('about.aboutpage',),
        ),
    ]
