# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='state',
            field=models.CharField(choices=[('R', 'Under Review'), ('B', 'Blocked'), ('U', 'Under Beta'), ('N', 'Normal')], default='R', max_length=1),
        ),
    ]
