# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171012_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
    ]
