# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 05:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(choices=[(1, 'x liked your post'), (2, 'User saved your post'), (3, 'x agreed'), (4, 'x disagreed'), (5, 'x reviewed'), (6, 'x attending'), (7, 'reported your content'), (8, 'removed your content'), (9, 'removed others content that you reported'), (0, 'Global Alert')])),
                ('related_user', models.CommaSeparatedIntegerField(blank=True, max_length=255)),
                ('related_user_count', models.IntegerField(default=0)),
                ('related_entity_id', models.IntegerField(blank=True)),
                ('related_entity_title', models.CharField(blank=True, max_length=255)),
                ('content', models.CharField(blank=True, max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=100)),
                ('link_url', models.CharField(blank=True, max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
