# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfCreation', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=30)),
                ('sub_reason', models.CharField(max_length=30)),
                ('explaination', models.CharField(blank=True, max_length=200)),
                ('total_agree', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
                ('total_disagree', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
                ('final_decision_taken', models.BooleanField(default=False)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Disscussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionReportUserCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.DiscussionReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfCreation', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=30)),
                ('sub_reason', models.CharField(max_length=30)),
                ('explaination', models.CharField(blank=True, max_length=200)),
                ('total_agree', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
                ('total_disagree', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
                ('total_switch', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
                ('final_decision_taken', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostReportUserCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PostReport')),
                ('switch_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Column')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
