# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('url_suffix', models.CharField(max_length=100, unique=True)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('js', models.TextField(blank=True)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField(default=False)),
                ('staff_comment', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HelpReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('good', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.HelpPage')),
            ],
        ),
    ]
