# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('help', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helpreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpkeyword',
            name='help',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.HelpPage'),
        ),
        migrations.CreateModel(
            name='StaffHelpPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('help.helppage',),
        ),
    ]
